name: Android Sample

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - 'demo/android/agp4/**'
      - .github/workflows/Android-CI-agp4.yml

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  buildDemo:
    name: Build Android AGP 4 Demo JDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp4
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 8 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.distribution }} ${{ matrix.java_version }}
        uses: actions/setup-java@v2.4.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assembleDebug -S --warning-mode all
