name: Android Sample

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - 'demo/android/agp7/**'
      - .github/workflows/Android-CI-agp7.yml

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  buildDemo:
    name: Build Android AGP 7 Demo JDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp7
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v3.3.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assembleDebug -S --warning-mode all
