name: Build Plugin

on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build-and-test:
    name: Build Plugin JDK ${{ matrix.distribution }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v2.4.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-v2-gradle-build-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-v2-gradle-build-
            ${{ runner.os }}-v2-gradle-
      - run: ./gradlew build
      - name: Upload Unit Test Results ${{ matrix.distribution }}-${{ matrix.java }}
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results ${{ matrix.distribution }}-${{ matrix.java }}
          path: build/test-results/**/*.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
