name: Build Plugin

on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build-and-test:
    name: Build Plugin JDK ${{ matrix.distribution }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v2.4.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-v2-gradle-build-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-v2-gradle-build-
            ${{ runner.os }}-v2-gradle-
      - run: ./gradlew build
