name: Android AGP 7 Demo CI (unreleased plugin version)

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'plugin-gradle/**'
      - 'demo/android/agp7/**'
      - .github/workflows/demo-android-agp7-ci-unreleased.yml
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - 'plugin-gradle/**'
      - 'demo/android/agp7/**'
      - .github/workflows/demo-android-agp7-ci-unreleased.yml

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  buildDemo:
    name: Build Android AGP 7 Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp7
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
        distribution: [ "zulu" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v3.9.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project Android AGP 7 Demo (unreleased plugin version)
        run: ./gradlew assembleDebug -S --warning-mode all  -I ../../../gradle/init.gradle.kts -Porg.jsonschema2dataclass.internal.spotless.disable=true  -Porg.jsonschema2pojo.internal.local=true
