name: Android AGP 7 Demo CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'plugin-gradle/**'
      - 'gradle/**'
      - 'gradlew*'
      - 'buildSrc/**'
      - settings.gradle.kts
      - build.gradle.kts
      - gradle.properties
      - 'demo/android/agp7/**'
      - .github/workflows/demo-android-agp7-ci.yml
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - 'plugin-gradle/**'
      - 'gradle/**'
      - 'gradlew*'
      - 'buildSrc/**'
      - settings.gradle.kts
      - build.gradle.kts
      - gradle.properties
      - 'demo/android/agp7/**'
      - .github/workflows/demo-android-agp7-ci.yml

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  buildDemo:
    name: Build Android AGP 7 Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp7
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 18 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v3.9.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project
        run: ./gradlew assembleDebug -S --warning-mode all
