name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'demo/android/agp4/gradle/**'
      - 'demo/android/agp7/gradle/**'
      - 'demo/java/gradle/**'
      - .github/workflows/gradle-wrapper-validation.yml
  pull_request:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'demo/android/agp4/gradle/**'
      - 'demo/android/agp7/gradle/**'
      - 'demo/java/gradle/**'
      - .github/workflows/gradle-wrapper-validation.yml
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process

jobs:
  validationPlugin:
    name: "Wrapper validation: Plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
  validationJavaKotlinSample:
    name: "Wrapper validation: Java Demo"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/java
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
  validationAndroidAgp7Sample:
    name: "Wrapper validation: Android AGP 7 Demo"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android-agp7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
