name: Update Gradle Wrapper RC

#on:
#  schedule:
#    - cron: "0 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update gradle
        id: gradleUpdate
        uses: EdwarDDay/upgrade-gradle-action@v1
        with:
          distribution-type: bin
          release-channel: release-candidate
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          title: "Update gradle wrapper to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          branch: "gradle_update_rc/plugin/version_${{ steps.gradleUpdate.outputs.gradle-version }}"
          body: |
            ${{ steps.gradleUpdate.outputs.version-information }}

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          labels: release candidate
