name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'demo/*/*/gradle/**'
      - 'demo/*/*/gradlew'
      - 'demo/*/*/gradlew.bat'
      - 'buildSrc/gradle*'
      - .github/workflows/gradle-wrapper-validation.yml
  pull_request:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'gradlew*'
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process

jobs:
  validationPlugin:
    name: "Wrapper validation: Plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  validationJavaKotlinSample:
    name: "Wrapper validation: Java Kotlin DSL Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/java/kotlin
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  validationJavaGroovySample:
    name: "Wrapper validation: Java Groovy DSL Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/java/groovy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  validationAndroidAgp7Sample:
    name: "Wrapper validation: Android AGP 7 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  validationAndroidAgp4Sample:
    name: "Wrapper validation: Android AGP 4 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  validationAndroidAgp3Sample:
    name: "Wrapper validation: Android AGP 3 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
