name: Update Gradle Wrapper RC

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'demo/*/*/gradle/**'
      - 'demo/*/*/gradlew'
      - 'demo/*/*/gradlew.bat'
      - .github/workflows/gradle-wrapper-update.yml
  pull_request:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'demo/*/*/gradle/**'
      - 'demo/*/*/gradlew'
      - 'demo/*/*/gradlew.bat'
      - .github/workflows/gradle-wrapper-update.yml
jobs:
  updateWrapperPlugin:
    name: "Gradle Wrapper Update RC: Plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: release candidate
          path-ignore: demo/**
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperJavaKotlinSample:
    name: "Gradle Wrapper Update RC: Java Kotlin DSL Sample"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          path: demo/java/kotlin
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  validationJavaModelPublishSample:
    name: "Gradle Wrapper Update RC: Java Kotlin DSL Sample"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          path: demo/java/model-publish
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperJavaGroovySample:
    name: "Gradle Wrapper Update RC: Java Groovy DSL Sample"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          path: demo/java/groovy
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperAndroidAgp7Sample:
    name: "Gradle Wrapper Update RC: Android AGP 7 Sample"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          path: demo/android/agp7
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperAndroidAgp4Sample:
    name: "Gradle Wrapper Update RC: Android AGP 4 Sample"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          path: demo/android/agp4
          release-channel: release-candidate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
