name: Build Plugin CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'plugin-gradle/**'
      - 'gradle/**'
      - 'gradlew*'
      - 'internal/**'
      - settings.gradle.kts
      - build.gradle.kts
      - gradle.properties
      - .github/workflows/plugin-build-ci.yml
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths:
      - 'plugin-gradle/**'
      - 'gradle/**'
      - 'gradlew*'
      - 'internal/**'
      - settings.gradle.kts
      - build.gradle.kts
      - gradle.properties
      - .github/workflows/plugin-build-ci.yml

env:
  GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build-and-test:
    name: Build Plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java: [ 11, 17, 19 ]
        distribution: [ "zulu", "temurin" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java }}
        uses: actions/setup-java@v3.9.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: gradle
      - run: ./gradlew build --warning-mode all --no-daemon -Porg.jsonschema2dataclass.internal.spotless.disable=true
