name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 6 * * MON"

jobs:
  updateWrapperPlugin:
    name: "Update Gradle Wrapper: Plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperJavaKotlinSample:
    name: "Update Gradle Wrapper: Java Kotlin DSL Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/java/kotlin
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperJavaGroovySample:
    name: "Update Gradle Wrapper: Java Groovy DSL Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/java/groovy
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: true
  updateWrapperAndroidAgp7Sample:
    name: "Update Gradle Wrapper: Android AGP 7 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp7
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  updateWrapperAndroidAgp4Sample:
    name: "Update Gradle Wrapper: Android AGP 4 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp4
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  updateWrapperAndroidAgp3Sample:
    name: "Update Gradle Wrapper: Android AGP 3 Sample"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/agp3
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.17
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
